### ISSUE TITLE
add age-based MFT strategy

### ISSUE THREAD

**Issue by maciekboni** [bonilab/Temple-Malaria-Simulation#8]
In this option, we would be able to distribute drugs by age.  In the input file it would look something like

strategy_db:
  0:
    name: MyRwandaAgeBasedMFT
    type: MFTAgeBased
    therapy_ids: [0, 3, 4]
    age_boundaries: [ 2.7 , 5.5 ]

Individuals aged 0.0 to 2.699 would get therapy 0
Individuals aged 2.7 to 5.499 would get therapy 3
Individuals aged 5.5 or older would get therapy 4

**Comment by merlinvn** [comment]
The MFTAgeBasedStrategy facilitates the assignment of therapies based on the age of individuals within the simulation. 

Recognizing the computational cost of using floating-point arithmetic for age calculations, ages are stored as integer values. 

This approach necessitates slight adjustments to age boundaries for precise therapy assignment. For instance, instead of setting a boundary at 2.7 years, it is adjusted to 2.9999 years to inclusively capture all individuals aged 2. Given this consideration, the age boundaries are defined to the nearest lower whole number, ensuring that all individuals within a year are correctly categorized under the intended therapy regime.

`age_boundaries` value can set to 2.7 but the behavior underneath would happen similar to 2.9999.

Example configuration for Uganda-MFTAgeBased strategy:

```yaml
1:
  name: Uganda-MFTAgeBased
  type: MFTAgeBased
  therapy_ids: [0, 1, 2, 3]
  age_boundaries: [2.999, 5.9999, 10.9999]
```

This configuration indicates the therapy IDs to be applied within specified age ranges, with boundaries adjusted to ensure inclusivity of age groups as integer values within the simulation.

Implementation:
To ensure efficient therapy assignment, a mapping from each integer age to the corresponding therapy index is precomputed. This mapping eliminates the need for repetitive boundary checking when assigning therapies to individuals.

```cpp
void MFTAgeBasedStrategy::build_map_age_to_therapy_index() {
  map_age_to_therapy_index.clear();
  constexpr int max_age = 100;
  size_t age_boundaries_index = 0;

  for (int age = 0; age < max_age; age++) {
    while (age_boundaries_index < age_boundaries.size() && age >= age_boundaries[age_boundaries_index]) {
      age_boundaries_index++;
    }
    auto therapy_index = age_boundaries_index;
    map_age_to_therapy_index.push_back(therapy_index);
  }
}

Therapy* MFTAgeBasedStrategy::get_therapy(Person* person) {
  if (person->age() >= age_boundaries.back()) { 
    return therapy_list.back(); 
  }
  return therapy_list[map_age_to_therapy_index[person->age()]];
}
```
The `build_map_age_to_therapy_index` function precomputes a mapping for each age to the appropriate therapy index based on the adjusted age boundaries. The get_therapy function then uses this mapping to quickly retrieve the correct therapy for a person based on their age, avoiding the computational overhead of dynamic boundary checking.

This enhanced approach ensures that the simulation can assign therapies efficiently, adapting to the integer-based age representation while maintaining accurate adherence to the intended age boundaries for therapy assignment.

NOTE: The `age_boundaries` are expected to be provided in ascending order.

https://github.com/bonilab/Temple-Malaria-Simulation/commit/9891523cf952236c1cfeac4e429e2602015017c6

**Comment by merlinvn** [comment]
In new implementation, a binary search algorithm is used to efficiently determine the appropriate therapy for individuals within specific age ranges. This update ensures O(log n) performance, making the process faster and more scalable.

This update introduces precise age boundaries represented as floating-point numbers to define distinct age bands for therapy assignment.

```yaml
1:
  name: Uganda-MFTAgeBased
  type: MFTAgeBased
  therapy_ids: [0, 1, 2, 3]
  age_boundaries: [2.5, 5.8, 10.12]
```

Individuals aged 0.0 to 2.4999 would get therapy 0
Individuals aged 2.5 to 5.7999 would get therapy 1
Individuals aged 5.8 or 10.1199 would get therapy 2
Individuals aged 10.12 or older would get therapy 3

For more details, please refer to the [commit changes](https://github.com/bonilab/Temple-Malaria-Simulation/commit/cdee598f05ef0fd2d0ec73a020a8783b82245722) on GitHub.

**Comment by merlinvn** [comment]
## Test case 1: Age boundaries has only 1 element

```cpp
    std::vector<double> age_boundaries = {5.5};
    std::vector<double> sample_ages = { 2, 5.5, 20};

    for (auto age : sample_ages) {
        auto index = find_age_range_index(age_boundaries, age);
        std::cout << "The age " << age << " will receive therapy at index:" << index << std::endl;
    }
```
output:

```
The age 2 will receive therapy at index:0
The age 5.5 will receive therapy at index:1
The age 20 will receive therapy at index:1
```

## Test case 2: Age boundaries has multiple elements

```cpp
    std::vector<double> age_boundaries = {2.7, 5.5, 10.8, 20.8};
    std::vector<double> sample_ages = {-1, 2, 2.7, 4, 5.5, 8, 10.8, 15, 20.8, 30};

    for (auto age : sample_ages) {
        auto index = find_age_range_index(age_boundaries, age);
        std::cout << "The age " << age << " will receive therapy at index:" << index << std::endl;
    }
```

output:
```
The age -1 will receive therapy at index:0
The age 2 will receive therapy at index:0
The age 2.7 will receive therapy at index:1
The age 4 will receive therapy at index:1
The age 5.5 will receive therapy at index:2
The age 8 will receive therapy at index:2
The age 10.8 will receive therapy at index:3
The age 15 will receive therapy at index:3
The age 20.8 will receive therapy at index:4
The age 30 will receive therapy at index:4
```
